### ISSUE TITLE
Doesn't work in PF2. 

### ISSUE THREAD

**Issue by apoapostolov** [Daimakaicho/cleaner-sheet-title-bar#2]
Checked with Culprit no mods.

**Comment by Daimakaicho** [comment]
Thanks for your feedback! I'll look into it.

**Comment by Daimakaicho** [comment]
This was a more general issue. Everything is fixed now. I did a quick try on a PF2e world and everything looks fine. I don't play PF2e though so if you notice some issues, your feedback are welcome!
