### ISSUE TITLE
Doesn't seem to remove the text

### ISSUE THREAD

**Issue by paulcheeba** [Daimakaicho/cleaner-sheet-title-bar#3]
It doesn't look like the title bar has been modified.
![image](https://user-images.githubusercontent.com/75949480/127916029-0f613eec-24a7-4637-89fd-c88319d918f8.png)

I loaded your module, and unloaded my version to be sure, there are no errors reported from your module. I tested in both FF and Chrome.

**Comment by Daimakaicho** [comment]
Thanks for your feedback! I'll look into it.

**Comment by paulcheeba** [comment]
Its working as of 1.2.2

**Comment by Daimakaicho** [comment]
I confirm v1.2.2 fix installation issue.
