### ISSUE TITLE
Feature Request: add a setting to keep, remove, or change Action text

### ISSUE THREAD

**Issue by Merudo** [Daimakaicho/cleaner-sheet-title-bar#5]
This might be outside the scope of the module, but it would be great if there would be an option to keep or change the text of some of the actions.

I'd like to keep "Sheet" as it for example, and rename "Prototype Token" to just "Token".  It could clean up the sheet but still provide indication for some of the more useful actions.

**Comment by Daimakaicho** [comment]
Thanks for your feedback ! I think however this should be managed by a new module which change button text : this will be 100% compatible with this module.

However, despite this feature is easily doable for native foundry buttons, I can't think to a nice way to handle buttons added by other modules unless adding special code for each module.
