### ISSUE TITLE
hover tooltip not working for journal entries

### ISSUE THREAD

**Issue by modzy2** [Daimakaicho/cleaner-sheet-title-bar#6]
Thanks for this module.

mouse hover over an icon is not showing the 'tooltip' name popup for journal entries

**Comment by Daimakaicho** [comment]
I notices this issue on some windows (but not all) but didn't had time to fix it yet. I'll try to free some time this week or next one to fix this.

**Comment by Daimakaicho** [comment]
This issue has been fixed in release v1.3.5.
