### ISSUE TITLE
Errors when using Wall Height

### ISSUE THREAD

**Issue by Zamrod** [Daimakaicho/cleaner-sheet-title-bar#7]
Errors appearing in console when using some other modules. Notably, Wall Height. 
![](https://media.discordapp.net/attachments/722566083499786352/954249438036115487/unknown.png)

**Comment by Daimakaicho** [comment]
Hi ! Thanks for you feedback. I try to reproduce this issue. Can you tell me what you are doing to get this error message ?

**Comment by Zamrod** [comment]
I believe it happens when you are mousing over wall vertexes using Wall Height and its pop up appears.

**Comment by Daimakaicho** [comment]
I released v1.3.6 to add WallHeight tooltip support. This was a very specific bug when WallHeight display a tooltip when one is already displayed. With new version, WallHeight tooltips are now ignored .
