### ISSUE TITLE
Hype button text from Maestro module still shows

### ISSUE THREAD

**Issue by hitokiri1337** [Daimakaicho/cleaner-sheet-title-bar#8]
Hype button from the Maestro module still shows its text in sheet title bars

![image](https://user-images.githubusercontent.com/38703108/169662739-68fd0b64-411d-4cda-b48b-969cb13243c4.png)

https://foundryvtt.com/packages/maestro

**Comment by Daimakaicho** [comment]
Hello and thanks for your feedback ! I released an update (v1.3.7) with a compatibility fix with Maestro module, you just have to update your module 👍
